// GENERATED by scripts/build-difficulty-colors.mjs — do not edit by hand.
//
// The question text colour, one step per wager tier. A higher wager really
// does produce a harder question (lib/coherence.js turns the wager into the
// difficulty instruction in the generation prompt AND into the fact-bank
// filter), so this colour reports something true rather than decorating.
//
// Lightest green = easiest = smallest wager. Deepest = hardest = biggest.
//
// EVERY step clears 4.5:1 on the slate ground — measured, not assumed. The
// ramp deepens toward sage rather than toward black precisely so the hardest
// question is still the most readable thing on screen. If these ever need
// re-tuning, change the targets in the generator and re-run it; do not hand-
// edit a hex here, because the whole point is that the contrast is proven.
//
// Ground: #2F4459
//   tier 0: #e5f1e7  8.64:1
//   tier 1: #c9e4cf  7.4:1
//   tier 2: #a3d8ad  6.21:1
//   tier 3: #7cce8c  5.29:1
//   tier 4: #46c560  4.5:1

export const DIFFICULTY_COLORS = [
  '#e5f1e7',
  '#c9e4cf',
  '#a3d8ad',
  '#7cce8c',
  '#46c560',
];

// Contrast of each step against the slate ground, kept alongside the colours
// so a future change can be checked without re-deriving it.
export const DIFFICULTY_CONTRAST = [8.64, 7.4, 6.21, 5.29, 4.5];

// Safe for any tier index, including a wager that somehow fell outside the
// ladder (Double Down doubles past the top tier).
export function difficultyColor(tierIndex) {
  const i = Math.max(0, Math.min(DIFFICULTY_COLORS.length - 1, tierIndex ?? 0));
  return DIFFICULTY_COLORS[i];
}
