"""
Crime-scene map layout — top-down, deliberately plain, zero API cost.

WHY THIS IS NOT GENERATED BY CLAUDE
-----------------------------------
The obvious design is to ask the generation prompt for coordinates alongside
everything else. This does not, and should not:

  * Cost. The stated goal is one prompt that returns the mystery, witnesses,
    clues and layout as cheaply as possible. Coordinates are the one part of
    that list a computer can derive for free, so paying tokens for them buys
    nothing.
  * Reliability. Every field added to that schema is another chance for the
    response to fail to parse -- and an old batch summary in
    mystery_database/generated/ shows 13 of 14 generations failing on exactly
    that. Geometry is the easiest thing to drop from the schema.
  * Quality. An LLM asked for rectangles produces overlapping rectangles.
    A packer does not.

So the prompt stays responsible for *meaning* -- which areas exist, what is in
them, who is standing where -- and this module is responsible for presentation.
Same mystery in, same map out, always: every placement is seeded from the
mystery's own title.

WHAT IT NEEDS FROM THE MYSTERY
------------------------------
`investigation_areas` (the areas become the rooms) and `characters` (witnesses
get placed). A mystery with no areas gets no map, and that is reported rather
than papered over with invented rooms -- the playtest is meant to be testing
whether generation produces usable areas, so faking them would defeat it.

OUTPUT
------
A plain dict of rectangles and points, in a 0..width / 0..height space, for
Godot's `_draw()` and (later) the phone client's SVG to render identically:

    {"width", "height", "areas": [{id, name, x, y, w, h}],
     "witnesses": [{name, area_id, x, y}], "body": {area_id, x, y}, ...}
"""
import hashlib
import math

DEFAULT_WIDTH = 1000
DEFAULT_HEIGHT = 640

MARGIN = 24      # gap between the map edge and the outermost rooms
GAP = 14         # gap between adjacent rooms -- this is what makes them read
                 # as separate rooms rather than one grid


def _seed_fraction(*parts) -> float:
    """A stable float in [0, 1) derived from the given strings.

    Deliberately not `random` -- placements must be identical on every machine
    and every Python version, because the Godot host screen and the phone
    client have to draw the same map.
    """
    key = "\x1f".join(str(p) for p in parts).encode("utf-8")
    digest = hashlib.sha256(key).digest()
    return int.from_bytes(digest[:8], "big") / float(1 << 64)


def _grid_shape(n: int) -> tuple:
    """Columns and rows for n rooms, favouring a landscape arrangement."""
    if n <= 0:
        return 0, 0
    cols = math.ceil(math.sqrt(n))
    rows = math.ceil(n / cols)
    return cols, rows


def _row_rects(count: int, top: float, row_height: float, width: int) -> list:
    """Lay `count` rooms across one row, filling the full width.

    Filling the row matters: with a fixed cell width, a final row holding two
    of three cells leaves a hole that reads as a missing room rather than as
    the shape of the building.
    """
    usable = width - 2 * MARGIN - GAP * (count - 1)
    cell_w = usable / count
    return [
        {
            "x": round(MARGIN + i * (cell_w + GAP), 1),
            "y": round(top, 1),
            "w": round(cell_w, 1),
            "h": round(row_height, 1),
        }
        for i in range(count)
    ]


def _point_in(rect: dict, *seed_parts) -> tuple:
    """A stable point inside a rect, kept off the walls and out of the label."""
    fx = 0.18 + 0.64 * _seed_fraction("x", *seed_parts)
    fy = 0.34 + 0.52 * _seed_fraction("y", *seed_parts)   # 0.34 clears the name label
    return (
        round(rect["x"] + fx * rect["w"], 1),
        round(rect["y"] + fy * rect["h"], 1),
    )


def _best_area_for_crime(areas: list, mystery: dict) -> int:
    """Index of the area the body most plausibly belongs in.

    Word overlap between the crime text and each area's own words. Crude on
    purpose: when nothing matches, area 0 is a perfectly good answer, and a
    cleverer rule would be a silent source of surprise.
    """
    crime = mystery.get("crime", {}) or {}
    text = " ".join([
        str(crime.get("initial_discovery", "")),
        str(crime.get("what_happened", "")),
    ]).lower()
    words = {w.strip(".,;:'\"()") for w in text.split() if len(w) > 4}
    if not words:
        return 0

    best_idx, best_score = 0, 0
    for i, area in enumerate(areas):
        area_words = {
            w.strip(".,;:'\"()")
            for w in f"{area.get('name','')} {area.get('description','')}".lower().split()
            if len(w) > 4
        }
        score = len(words & area_words)
        if score > best_score:
            best_idx, best_score = i, score
    return best_idx


def build_map(mystery: dict, width: int = DEFAULT_WIDTH, height: int = DEFAULT_HEIGHT):
    """Return a layout dict for this mystery, or None if it has no areas."""
    areas = mystery.get("investigation_areas") or []
    if not areas:
        return None

    title = mystery.get("title", "untitled")
    cols, rows = _grid_shape(len(areas))
    usable_h = height - 2 * MARGIN - GAP * (rows - 1)
    row_h = usable_h / rows

    placed = []
    idx = 0
    for r in range(rows):
        in_row = min(cols, len(areas) - idx)
        top = MARGIN + r * (row_h + GAP)
        for rect, area in zip(_row_rects(in_row, top, row_h, width), areas[idx:idx + in_row]):
            placed.append({
                "id": area.get("id", f"A{idx + 1}"),
                "name": area.get("name", "Unnamed area"),
                "description": area.get("description", ""),
                **rect,
            })
            idx += 1

    witnesses = []
    witness_chars = [
        c for c in mystery.get("characters", [])
        if c.get("role") == "witness"
    ]
    for i, ch in enumerate(witness_chars):
        # Spread witnesses over distinct rooms first, then wrap. Two witnesses
        # in one room is fine; two witnesses in one room while three rooms sit
        # empty looks like a bug.
        area = placed[i % len(placed)]
        x, y = _point_in(area, title, "witness", ch.get("name", i))
        witnesses.append({
            "name": ch.get("name", "Witness"),
            "occupation": ch.get("occupation", ""),
            "area_id": area["id"],
            "x": x,
            "y": y,
        })

    body_area = placed[_best_area_for_crime(areas, mystery)]
    bx, by = _point_in(body_area, title, "body")

    return {
        "width": width,
        "height": height,
        "title": title,
        "areas": placed,
        "witnesses": witnesses,
        "body": {"area_id": body_area["id"], "x": bx, "y": by},
        "_derived": True,
    }
