# Shared constants — ported from lib/constants.js. Keep in sync with that
# file until the Next.js prototype is retired (see docs/WIRING.md).

ROUNDS = 4
QUESTIONS_PER_ROUND = 6
TOTAL_QUESTIONS = ROUNDS * QUESTIONS_PER_ROUND  # 24
MIN_WAGER = 50
MAX_WAGER = 500
RESULT_SCREEN_SECONDS = 4
STEAL_WINDOW_SECONDS = 8
MIN_PLAYERS = 3
MAX_PLAYERS = 6
CATEGORIES_PER_PLAYER = 5
CATEGORY_OPTIONS_COUNT = 6
CARD_PICK_TIMER_SECONDS = 40
RANDOM_CARDS_PER_ROUND = 2
FACTS_PER_CATEGORY = 10
CATEGORIES_PER_FETCH_BATCH = 3
DISCONNECT_GRACE_SECONDS = 45
AUTO_ADVANCE_AWAY_THRESHOLD = 2
LINEUP_COLOR_FLAVOR_CHANCE = 0.4
BASE_TIMER_SECONDS = 20
